secrets: /config/secrets.yaml
appdaemon:
  latitude: !secret zone_lat_home
  longitude: !secret zone_lon_home
  elevation: 146
  time_zone: Europe/London
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      client_host: "OptiSERVE.lan"
      client_user: !secret mqtt_user
      client_password: !secret mqtt_pass
      namespace: "mqtt"
      client_topics:
        - "OptiSERVE/#"
http:
  url: http://127.0.0.1:5050
hadashboard:
admin:
api:
