## Google Music Media Player
## Use this 'package.yaml' file to configure "gmusic_player"
media_player:
  - platform: gmusic_player
    device_id: !secret gmusic_device_id
    username: !secret gmusic_user
    password: !secret gmusic_pass
      
    ## Add your media_players below
    speakers: # Example media_players
      - main_speakers
      - bedroom_speaker
      - dining_room_speaker
      - living_room_speaker
      - kitchen_speaker
      - olivia_speaker
      - playroom_speaker
      
    ## Optional: enable streaming from gmusicproxy (Workaround for issue #6)
    ## https://github.com/tprelog/homeassistant-gmusic_player/issues/6
    gmusicproxy: !secret gmusic_proxy
