- name: Downstairs Lights Warm
  entities:
    light.living_room_lamp_1:
      brightness: 254
      color_temp: 370
      friendly_name: Living Room Lamp 1
      icon: mdi:lamp
      is_deconz_group: false
      max_mireds: 500
      min_mireds: 153
      state: 'on'
      supported_features: 43
    light.living_room_lamp_2:
      brightness: 254
      color_temp: 370
      friendly_name: Living Room Lamp 2
      icon: mdi:lamp
      is_deconz_group: false
      max_mireds: 500
      min_mireds: 153
      state: 'on'
      supported_features: 43
    light.living_room_lamp_3:
      brightness: 254
      color_temp: 370
      friendly_name: Living Room Lamp 3
      icon: mdi:lamp
      is_deconz_group: false
      max_mireds: 500
      min_mireds: 153
      state: 'on'
      supported_features: 43
    light.standing_lamp:
      brightness: 255
      effect_list:
      - colorloop
      friendly_name: Standing Lamp
      hs_color:
      - 30
      - 43.137
      icon: mdi:lamp
      is_deconz_group: false
      rgb_color:
      - 255
      - 200
      - 145
      state: 'on'
      supported_features: 61
      xy_color:
      - 0.443
      - 0.379
    switch.radiator_light:
      friendly_name: Radiator Light
      icon: mdi:radiator
      state: 'on'
    switch.tv_back_light:
      friendly_name: TV Back Light
      icon: mdi:monitor
      state: 'off'
    light.dining_room_lamp_1:
      state: "on"
    light.dining_room_lamp_2:
      state: "on"

- name: TV Time
  entities:
    light.living_room_lamp_1:
      state: on
      brightness: 170
    light.living_room_lamp_2:
      state: on
      brightness: 170
    light.living_room_lamp_3:
      state: on
      brightness: 170
    light.standing_lamp:
      state: off
    light.dining_room_lamp_1:
      state: on
      brightness: 255
    light.dining_room_lamp_2:
      state: on
      brightness: 255
    light.hall_lamp:
      state: on
      brightness: 255
    switch.tv_back_light:
      state: on
    switch.radiator_light:
      state: on
    switch.living_room_unit_lights:
      state: on
    # input_boolean.full_recline:
    #   state: on