

- alias: Doorbell Notifications
  trigger:
    platform: state
    entity_id: binary_sensor.tecknet_door_bell
    to: 'on'
  action:
  - service: notify.john
    data:
      title: Doorbell
      message: There's somebody at the door ha ha!
      data:
        photo:
          - url: http://192.168.7.1:5110/driveway/person/best.jpg
        channel: Doorbell

- alias: Door Chime
  trigger:
    platform: state
    entity_id: binary_sensor.tecknet_door_bell
    to: 'on'
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.downstairs_speakers
      # media_content_id: https://www.soundjay.com/door/doorbell-1.mp3
      media_content_id: !secret media_door_bell
      media_content_type: music