  alias: School Bell
  description: '"Home School" bells during lockdown'
  trigger:
    - platform: time
      at: "08:50:00"
    - platform: time
      at: "10:15:00"
    - platform: time
      at: "10:30:00"
    - platform: time
      at: "12:30:00"
    # - platform: time
    #   at: "13:30:00"
    - platform: time
      at: "15:15:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.turn_on
      entity_id: script.school_bell