- platform: mqtt
  name: "TRC - Middle Button"
  state_topic: "tradfri/remote/middle"
  expire_after: 1

- platform: mqtt
  name: "TRC - Top Button"
  state_topic: "tradfri/remote/top"
  expire_after: 1

- platform: mqtt
  name: "TRC - Bottom Button"
  state_topic: "tradfri/remote/bottom"
  expire_after: 1

- platform: mqtt
  name: "TRC - Left Button"
  state_topic: "tradfri/remote/left"
  expire_after: 1

- platform: mqtt
  name: "TRC - Right Button"
  state_topic: "tradfri/remote/right"
  expire_after: 1