# - platform: yr
#   name: Weather
#   monitored_conditions:
#     - temperature
#     - symbol
#     - precipitation
#     - windSpeed
#     - pressure
#     - windDirection
#     - humidity
#     - fog
#     - cloudiness
#     - lowClouds
#     - mediumClouds
#     - highClouds
#     - dewpointTemperature

# - platform: yr
#   name: Weather Tomorrow
#   forecast: 24
#   monitored_conditions:
#     - temperature
#     - symbol
#     - precipitation
#     - windSpeed
#     - pressure
#     - windDirection
#     - humidity
#     - fog
#     - cloudiness
#     - lowClouds
#     - mediumClouds
#     - highClouds
#     - dewpointTemperature

- platform: darksky
  api_key: !secret dark_sky_key
  # forecast:
  #   - 0
  # hourly_forecast:
  #   - 0
  #   - 1
  monitored_conditions:
    - icon
    - summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - humidity
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - wind_speed
    - wind_bearing
    - precip_type
    - precip_probability
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - uv_index
    - daily_summary
    - pressure
    - visibility
  scan_interval:
    minutes: 5

# - platform: illuminance
#   entity_id: sensor.dark_sky_icon
# - platform: illuminance
#   name: DSW Illuminance
#   entity_id: weather.dark_sky
# - platform: illuminance
#   name: YRS Illuminance
#   entity_id: sensor.yr_symbol

- platform: template
  sensors:
    cloud_cover:
      entity_id: sensor.dark_sky_cloud_coverage
      friendly_name: Cloud Cover
      value_template: '{{ states.sensor.dark_sky_cloud_coverage.state|float > 60 }}'
    average_room_temp:
      friendly_name: "Average Temperature"
      value_template: ''
      unit_of_measurement: "°C"
      device_class: temperature

- platform: template
  sensors:
    sunlight_pct:
      entity_id:
        - sun.sun
        - sensor.dark_sky_cloud_coverage
      value_template: >-
        {%- set elevation = state_attr('sun.sun','elevation') | float %}
        {%- set cloud_coverage = states('sensor.dark_sky_cloud_coverage') | float %}
        {%- set cloud_factor = (1 - (0.75 * ( cloud_coverage / 100) ** 3 )) %}
        {%- set min_elevation = -6 %}
        {%- set max_elevation = 90 %}
        {%- set adjusted_elevation = elevation - min_elevation %}
        {%- set adjusted_elevation = [adjusted_elevation,0] | max %}
        {%- set adjusted_elevation = [adjusted_elevation,max_elevation - min_elevation] | min %}
        {%- set adjusted_elevation = adjusted_elevation / (max_elevation - min_elevation) %}
        {%- set adjusted_elevation = adjusted_elevation %}
        {%- set adjusted_elevation = adjusted_elevation * 100 %}
        {%- set brightness = adjusted_elevation * cloud_factor %}
        {{ brightness | round }}
      unit_of_measurement: '%'
      device_class: 'illuminance'
    # outside_lux:
    #   friendly_name: "Outside Lux"
    #   unit_of_measurement: 'lx'
    #   value_template: ""
    #   device_class: 'illuminance'